export const USER_ACTION_TYPE = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    GOOGLE_SIGNIN_START: 'user/GOOGLE_SIGNIN_START',
    EMAIL_SIGNIN_START: 'user/EMAIL_SIGNIN_START', 
    SIGNIN_SUCCESS: 'user/SIGNIN_SUCCESS',
    SIGNIN_FAILED: 'user/SIGNIN_FAILED',
    SIGNUP_START: 'user/SIGNUP_START',
    SIGNUP_SUCCESS: 'user/SIGNUP_SUCCESS',
    SIGNUP_FAILED: 'user/SIGNUP_FAILED',
    SIGNOUT_START: 'user/SIGNOUT_START',
    SIGNOUT_SUCCESS: 'user/SIGNOUT_SUCCESS',
    SIGNOUT_FAILED: 'user/SIGNOUT_FAILED',
}